### ISSUE TITLE
Failed to upload

### ISSUE THREAD

**Issue by garudaonekh** [py32duino/Arduino-PY32#4]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

Hi,
I use PY32F002AF15P6TU dev board
Upload failed with the following error:
`fail to reset device to boot status, timeout`

I use this board: https://www.taobao.com/list/item/734980118695.htm

### 描述您想要的解决方案 / Describe the solution you'd like

Please note the board come with WCH340 chip.

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

I try to change baudrate to 9600 but still failed. I also try to set PB6 to high but still failed

### 确认信息

- [X] 检查过该需求，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 这个需求是真实存在的，并且对于本项目来说是必要的
- [X] 我已经提供了该需求的清晰、详细、完整的方案，请按该方案进行实施
- [X] 我认为我提供的信息已经足够，不需要其他人继续完善该需求的其他细节
- [X] 我同意跟进该需求的实施进程，并在适时提供合理的解释与纠正

**Comment by garudaonekh** [comment]
[2196488812PY32F002AF15P-V1.0.pdf](https://github.com/py32duino/Arduino-PY32/files/13533984/2196488812PY32F002AF15P-V1.0.pdf)
Hi, here's its schema.

**Comment by garudaonekh** [comment]
Now, it works.

**Comment by HalfSweet** [comment]
With all due respect, this is a very bad design. There is a lot about it's design that doesn't meet the specs.

If you expect to get automatic downloads, you might want to look at this design
<https://github.com/HalfSweet/PY32F030K28U_Arduino_Nano>
